# Generated by Django 6.0 on 2026-03-28 14:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_date', models.DateField(help_text='The date of the statement')),
                ('description', models.CharField(blank=True, help_text='e.g., May 2024 Statement', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='tracker.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-statement_date'],
                'unique_together': {('user', 'account', 'statement_date')},
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='statement',
            field=models.ForeignKey(blank=True, help_text='Optional — the statement this transaction belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='tracker.statement'),
        ),
    ]
