# Generated by Django 6.0 on 2026-03-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_account_balance_statement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_recurring',
        ),
        migrations.AddField(
            model_name='transaction',
            name='recurring_period',
            field=models.CharField(blank=True, choices=[('', 'Non-recurring'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly (1/3 per month)'), ('yearly', 'Yearly (1/12 per month)')], default='', help_text='Leave blank for non-recurring; otherwise specifies how often this transaction repeats', max_length=12),
        ),
    ]
